- Resources/controls/App_LocalResources/Address.ascx.nl-NL.resx
- Resources/controls/App_LocalResources/SkinControl.ascx.nl-NL.resx
- Resources/controls/App_LocalResources/UrlTrackingControl.ascx.nl-NL.resx
- Resources/controls/App_LocalResources/User.ascx.nl-NL.resx
Correcties, zodat de kwaliteit van de vertaling toeneemt.
> Tekstuele correcties

- Resources/DNNCE_nl-NL.dnn
> Straighten DNN manifest.

- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Pages/App_LocalResources/pages.nl-NL.resx
> Fixes merge errors on pages.nl-NL.resx

- Resources/Portals/_default/Blank Website.template.nl-NL.resx
- Resources/Portals/_default/Default Website.template.nl-NL.resx
> Default site templates with dummy organisation

- Resources/App_GlobalResources/GlobalResources.nl-NL.resx
> Do not translate Home tab name to Thuis

- Resources/Portals/_default/Blank Website.template.nl-NL.resx
- Resources/Portals/_default/Default Website.template.nl-NL.resx
> Correcting typo's and streamlining text

- readme.md
> Expanding the readme with instructions how to contribute

- Resources/App_GlobalResources/Exceptions.nl-NL.resx
> Translation corrections in Exceptions

- readme.md
> Starting with a list of stand terms in translations

- .github/COMMON_TERMS.md
> Update and technical term

- .github/workflows/updateVersions.yml
This creates an action to update the versions in manifests when a new release branch is created.
> Create update version action

- Resources/DNNCE_nl-NL.dnn
> Put DataConsent .resx file to the correct folder

- .github/COMMON_TERMS.md
> Extend the list of common terms and translations

- Resources/App_GlobalResources/GlobalResources.nl-NL.resx
- Resources/admin/Modules/App_LocalResources/Export.ascx.nl-NL.resx
- Resources/admin/Modules/App_LocalResources/Import.ascx.nl-NL.resx
- Resources/admin/Modules/App_LocalResources/ModuleLocalization.ascx.nl-NL.resx
- Resources/admin/Modules/App_LocalResources/ModulePermissions.ascx.nl-NL.resx
- Resources/admin/Modules/App_LocalResources/ModuleSettings.ascx.nl-NL.resx
- Resources/admin/Modules/App_LocalResources/ViewSource.ascx.nl-NL.resx
- Resources/admin/Security/App_LocalResources/PasswordReset.ascx.nl-NL.resx
- Resources/admin/Security/App_LocalResources/SendPassword.ascx.nl-NL.resx
- Resources/admin/Skins/App_LocalResources/User.ascx.nl-NL.resx
- Resources/admin/Tabs/App_LocalResources/Export.ascx.nl-NL.resx
- Resources/admin/Tabs/App_LocalResources/Import.ascx.nl-NL.resx
Admin sectie nagelopen.
Ook GlobalResources zit erbij.
> Issue #46: Change U/Uw into Jij/Jouw in admin\

- Resources/Providers/FolderProviders/AzureFolderProvider/App_LocalResources/settings.ascx.nl-NL.resx
- Resources/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/browser.aspx.nl-NL.resx
- Resources/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/editorconfigmanager.ascx.nl-NL.resx
- Resources/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/options.aspx.nl-NL.resx
> Aanpassen U/uw naar Jij/Jouw & vele tekstuele verbeteringen

- Resources/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
- Resources/Install/App_LocalResources/UpgradeWizard.aspx.nl-NL.resx
> Update Install LP, u/uw into jij/jouw

- Resources/Portals/_default/Blank Website.template.nl-NL.resx
- Resources/Portals/_default/Default Website.template.nl-NL.resx
> Update site templates with better words, u/uw into jij/jouw

- .github/COMMON_TERMS.md
> Update and improve common terms

- Resources/App_GlobalResources/Exceptions.nl-NL.resx
- Resources/App_GlobalResources/FileUpload.nl-NL.resx
- Resources/App_GlobalResources/GlobalResources.nl-NL.resx
- Resources/App_GlobalResources/SharedResources.nl-NL.resx
- Resources/App_GlobalResources/WebControls.nl-NL.resx
> Update nl-NL for GlobalResources

- Resources/App_GlobalResources/GlobalResources.nl-NL.resx
> Finetuning GlobalResources

- Resources/ReleaseNotes.txt
> Updated release notes for the next version of DNN

- .github/COMMON_TERMS.md
> Update common terms

- Resources/App_GlobalResources/SharedResources.nl-NL.resx
- Resources/DesktopModules/Admin/Authentication/App_LocalResources/Login.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/App_LocalResources/tabs.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Pages/App_LocalResources/pages.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.SiteSettings/App_LocalResources/sitesettings.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Sites/App_LocalResources/sites.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Users/App_LocalResources/users.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/EditRoles.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/ManageUsers.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/Roles.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/SecurityRoles.ascx.nl-NL.resx
- Resources/DesktopModules/SocialGroups/App_LocalResources/SharedResources.nl-NL.resx
- Resources/admin/Modules/App_LocalResources/ModuleSettings.ascx.nl-NL.resx
- Resources/admin/Security/App_LocalResources/SendPassword.ascx.nl-NL.resx
> Small textual corrections and typo's corrections

- LICENSE
- Resources/license.txt
> Update .NET license to standard text

- .editorconfig
- .gitignore
> Manage CRLF for the editor

- Resources/Portals/_default/Default Website.template.nl-NL.resx
> Update social links

- Resources/App_GlobalResources/Exceptions.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Servers/App_LocalResources/servers.nl-NL.resx
- Resources/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
- Resources/Portals/_default/Blank Website.template.nl-NL.resx
- Resources/Portals/_default/Default Website.template.nl-NL.resx
- Resources/ReleaseNotes.txt
- Resources/admin/Modules/App_LocalResources/ModuleSettings.ascx.nl-NL.resx
- readme.md
> Updates for DNN962

- Resources/App_GlobalResources/GlobalResources.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Extensions/App_LocalResources/extensions.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Licensing/App_LocalResources/licensing.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Pages/App_LocalResources/pages.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Prompt/App_LocalResources/prompt.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Security/App_LocalResources/security.nl-NL.resx
- Resources/DesktopModules/Admin/FiftyOneClientCapabilityProvider/App_LocalResources/Administration.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/HtmlEditorManager/App_LocalResources/providerconfiguration.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/HtmlEditorManager/Controls/App_LocalResources/InvalidConfiguration.ascx.nl-NL.resx
- Resources/DesktopModules/DDRMenu/App_LocalResources/MenuView.ascx.nl-NL.resx
- Resources/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
- Resources/Install/App_LocalResources/UpgradeWizard.aspx.nl-NL.resx
- Resources/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/browser.aspx.nl-NL.resx
- Resources/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/options.aspx.nl-NL.resx
- Resources/admin/Skins/App_LocalResources/Search.ascx.nl-NL.resx
> Update http: to https: in documentation and references

- Resources/App_GlobalResources/SharedResources.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/EditProfileDefinition.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/Profile.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/Register.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/SharedResources.nl-NL.resx
kleine verbeteringen, vooral weergave naam op registratie scherm stond er nogal verwarrend op.
> Opschonen van registration velden

- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Pages/App_LocalResources/pages.nl-NL.resx
> Improve PB Pages nl-NL text elements

- .github/COMMON_TERMS.md
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Servers/App_LocalResources/servers.nl-NL.resx
- Resources/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
- Resources/ReleaseNotes.txt
- Resources/admin/Modules/App_LocalResources/ModuleSettings.ascx.nl-NL.resx
- readme.md
> Updates for new release DNN970

- Resources/App_GlobalResources/prompt.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Security/App_LocalResources/security.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Users/App_LocalResources/users.nl-NL.resx
> Correction of typo's and text improvements

- Resources/ReleaseNotes.txt
> Update LP release notes

- Resources/ReleaseNotes.txt
- readme.md
Update for DNN 09.07.02
Close #118
> Improving the readme.md for the new version

- Resources/ReleaseNotes.txt
> Improve lay-out release notes

- Resources/App_GlobalResources/SharedResources.nl-NL.resx
- Resources/DesktopModules/DigitalAssets/App_LocalResources/EditFolderMapping.ascx.nl-NL.resx
Je heeft -->>> Je hebt
Sekecteerd de --> Selecteer de
> Two minor spelling corrections

- Resources/App_GlobalResources/SharedResources.nl-NL.resx
- Resources/App_GlobalResources/prompt.nl-NL.resx
- Resources/DesktopModules/DigitalAssets/App_LocalResources/EditFolderMapping.ascx.nl-NL.resx
- Resources/ReleaseNotes.txt
> 2nd part Prompt translation to nl-NL and minor corrections

- readme.md
> Update readme with version release instructions

- Resources/DesktopModules/ResourceManager/App_LocalResources/editfoldermapping.ascx.nl-NL.resx
- Resources/DesktopModules/ResourceManager/App_LocalResources/resourcemanager.nl-NL.resx
- Resources/DesktopModules/ResourceManager/App_LocalResources/settings.ascx.nl-NL.resx
- Resources/DesktopModules/ResourceManager/App_LocalResources/view.ascx.nl-NL.resx
> nl-NL translations of ResourceManager

- Resources/ReleaseNotes.txt
> Description of changes, release notes V 09.10.00

- readme.md
> Update list of nl-NL releases

- Resources/DNNCE_nl-NL.dnn
Update `develop` to merge manifest changes from `release/9.10.0`.
> Merge `release/9.10.0` into `develop`

- Resources/App_GlobalResources/SharedResources.nl-NL.resx
- Resources/App_GlobalResources/prompt.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Extensions/App_LocalResources/extensions.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Users/App_LocalResources/users.nl-NL.resx
- Resources/ReleaseNotes.txt
- readme.md
> Updates for DNN 09.10.01 and corrections

- Resources/App_GlobalResources/GlobalResources.nl-NL.resx
Translation EMAIL_MESSAGING_DISPATCH_BODY
And some small text corrections
> GlobalResources.nl-NL.resx

- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.AdminLogs/App_LocalResources/adminlogs.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.Servers/App_LocalResources/servers.nl-NL.resx
- Resources/DesktopModules/Admin/Dnn.PersonaBar/Modules/Dnn.TaskScheduler/App_LocalResources/taskscheduler.nl-NL.resx
> Correcting translation errors + translation improvements

- Resources/DesktopModules/Admin/Authentication/App_LocalResources/Login.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/SearchResults/App_LocalResources/ResultsSettings.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/EditUser.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/ManageUsers.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/Membership.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/Password.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/Profile.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/ProfileDefinitions.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/Register.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/SharedResources.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/User.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Security/App_LocalResources/UserSettings.ascx.nl-NL.resx
A set of small text-corrections in the Admin section of the resourcefiles.
> Set of small text corrections

- Resources/DNNCE_nl-NL.dnn
> Commit new manifest versions

- Resources/App_GlobalResources/prompt.nl-NL.resx
- Resources/DesktopModules/Admin/HtmlEditorManager/App_LocalResources/providerconfiguration.ascx.nl-NL.resx
> Update providerconfiguration.ascx.nl-NL.resx and Prompt.nl-NL.resx

- Resources/App_GlobalResources/GlobalResources.nl-NL.resx
- Token FullName (depricated) replaced by DisplayName.
- Translations of ALL fields
> Corrections and translations in GlobalResources.nl-NL 

- Resources/App_GlobalResources/Prompt.nl-NL.resx
- Resources/App_GlobalResources/WebControls.nl-NL.resx
- Corrections
- Additions
- Completed the translation
- Changes to follow the guidelines for Dutch translation (u = jij)
> Updated files: Prompt and WebControls

- Resources/DesktopModules/Admin/Authentication/App_LocalResources/Login.ascx.nl-NL.resx
- Resources/DesktopModules/Admin/Console/App_LocalResources/Settings.ascx.nl-NL.resx
> Corrections and polishing - Login & Console
